=== Malek-Haba/SOA_TP1/bin/cinema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/cinema" xmlns:tns="http://www.example.org/cinema" elementFormDefault="qualified">


    <complexType name="producteur">
    	<sequence>
    		<element name="nom" type="string"></element>
    		<element name="Film" type="tns:Film"></element>
    	</sequence>
    </complexType>
    
    <element name="cinema" type="tns:cinema"></element>
    
    <complexType name="cinema">
    	<sequence>
    		<element name="Film" type="tns:Film"></element>
    		<element name="producteur" type="tns:producteur"></element>
    	</sequence>
    </complexType>

    <complexType name="Film">
    	<sequence>
    		<element name="titre" type="string"></element>
    		<element name="année" type="string"></element>
    		<element name="réalisateur" type="string"></element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    	<attribute name="type" type="string"></attribute>
    </complexType>
</schema>

=== Malek-Haba/SOA_TP1/bin/cinema.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:cinema xmlns:tns="http://www.example.org/cinema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/cinema cinema.xsd ">
  <tns:Film >
    <tns:titre>Les bronzes</tns:titre>
    <tns:année>1978</tns:année>
    <tns:réalisateur>Patrice Leconte</tns:réalisateur>
  </tns:Film>
  <tns:producteur>
    <tns:nom>Daniel Toscan du Plantier</tns:nom>
    <tns:Film >
      <tns:titre>tLes bronzes</tns:titre>
      <tns:année>1978</tns:année>
      <tns:réalisateur> Patrice Leconte</tns:réalisateur>
    </tns:Film>
    
  </tns:producteur>
</tns:cinema>
